version: "4"
services:
  redis:
    image: redis:alpine
  data-science-services:
    build: ./python-processing
    environment:
      - PYTHONPATH=user/src/app
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
    volumes:
      - ./python-processing/:/data/bin/bash
    working_dir: /data/bin/bash
    command: sh -c " pip install --upgrade pip && pip install -r pyproject.toml && flask run"
    ports:
      - "8000:5000"
networks:
  default:
    name: my-network
